### ISSUE TITLE
Trouble running - 'pandas'

### ISSUE THREAD

**Issue by castellanosr** [Accelegator/accelegator#76] opened 2017-11-07 20:35 UTC
When I try to run I get:
```shell
castellanosr@aldenv171:~/280 Projects/accelegator$ python3 accelegator.py
Traceback (most recent call last):
  File "accelegator.py", line 6, in <module>
    from queries import parse_csv_into_dataframe
  File "/home/c/castellanosr/280 Projects/accelegator/queries.py", line 4, in <module>
    import pandas
ImportError: No module named 'pandas'
castellanosr@aldenv171:~/280 Projects/accelegator$ 
```

If I am simply running this wrong we need to better explain how to run in the READme so it's easy for users.

**Comment by delgrecoj** [comment] 2017-11-07 20:37
Have you installed the dependencies with the `pip3 install --user -r requirements.txt` command?

Could you provide the full output?  The issue does not yet provide any information about the actual problem.

**Comment by castellanosr** [comment] 2017-11-07 20:39
Yes! I installed everything successfully.

**Comment by delgrecoj** [comment] 2017-11-07 20:42
Unable to reproduce.  The `requirements.txt` file lists `pandas`, so that module should be present when the program is ran, meaning that it complaining about missing that module makes no sense.

**Comment by lylet-AC** [comment] 2017-11-07 20:44
Upon installing pandas from the requirements.txt it outputs:

Exception:
Traceback (most recent call last):
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/l/lylet/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/pytz-2017.3.dist-info'

**Comment by delgrecoj** [comment] 2017-11-07 20:46
Are you certain you are using the `--user` flag?  The permission denied part looks like what I would expect to see without the flag, and without `sudo`.

**Comment by lylet-AC** [comment] 2017-11-07 20:48
That flag worked, but wasn't mentioned anywhere in the README.md

**Comment by delgrecoj** [comment] 2017-11-07 20:50
It is listed on the other repositories... I'll create an issue for that here as well.
@castellanosr does that solve your problem as well?

**Comment by lylet-AC** [comment] 2017-11-13 05:34
I added the `--user` flag to the documentation a while ago, can we close this issue?

**Comment by delgrecoj** [comment] 2017-11-13 13:32
@castellanosr never responded, so am unsure whether this fixes her issue.
Closing regardless; @castellanosr, if the issue persists, please open a new issue.

**Closed by delgrecoj** 2017-11-13 13:32 UTC

**Comment by castellanosr** [comment] 2017-11-14 03:54
I apologize for not responding earlier, but this did indeed fix the issue. Thank you for updating the READme.
